version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      # Install python deps
      - python -m venv venv
      - . venv/bin/activate
      - pip install -r requirements_dev.txt
  build:
    commands:
      - flake8
      - bandit .
      - coverage run -m py.test
  post_build:
    commands:
      - codecov
