version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - # Install postgres
      - docker run -e POSTGRES_DB=contracts_test -p 5432:5432 -d postgres:11.3

      # Install python deps
      - python -m venv venv
      - . venv/bin/activate
      - pip install -r requirements/dev.txt

      # Run migrations
      - flask db upgrade
  build:
    commands:
      - flake8
      - bandit .
      - coverage run -m py.test
  post_build:
    commands:
      - codecov
artifacts:
  files:
    - '**/*'